from datetime import datetime
from pathlib import Path

from ..models.results import Result, RunResult


class HtmlReporter:
    def write(self, run: RunResult, output_path: Path) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)

        by_module: dict[str, list] = {}
        for t in run.tests:
            by_module.setdefault(t.module, []).append(t)

        module_rows = ""
        for mod, tests in sorted(by_module.items()):
            total = len(tests)
            passed = sum(1 for t in tests if t.result == Result.OK)
            failed = total - passed
            status = "PASS" if failed == 0 else "FAIL"
            color = "#198754" if status == "PASS" else "#dc3545"
            module_rows += (
                f"<tr>"
                f"<td><code>{mod}</code></td>"
                f"<td style='color:{color};font-weight:bold'>{status}</td>"
                f"<td>{passed}/{total}</td>"
                f"</tr>"
            )

        failure_rows = ""
        for t in run.tests:
            if t.result != Result.NOK:
                continue
            for c in t.checks:
                if c.result != Result.NOK:
                    continue
                failure_rows += (
                    f"<tr>"
                    f"<td><code>{t.module}</code></td>"
                    f"<td><code>{t.test_case}</code></td>"
                    f"<td><code>{c.field}</code></td>"
                    f"<td><code>{c.expected!r}</code></td>"
                    f"<td><code>{c.found!r}</code></td>"
                    f"</tr>"
                )

        decision = run.release_decision or ("APPROVED" if run.failed == 0 else "REJECTED")
        d_color = "#198754" if decision == "APPROVED" else "#dc3545"
        pct = round(run.passed / run.total * 100) if run.total else 0

        failures_section = (
            "<h2>Failures</h2>"
            "<table><thead><tr>"
            "<th>Module</th><th>Test Case</th><th>Field</th><th>Expected</th><th>Found</th>"
            f"</tr></thead><tbody>{failure_rows}</tbody></table>"
        ) if failure_rows else "<p style='color:#198754'>&#10003; No failures.</p>"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Release Report — {run.run_id}</title>
<style>
  body  {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #212529; }}
  h1    {{ color: #0D3456; }}
  h2    {{ color: #0D3456; margin-top: 32px; }}
  .badge {{ display: inline-block; padding: 6px 18px; border-radius: 4px; color: #fff; font-weight: bold; font-size: 1.1rem; }}
  table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
  th    {{ background: #0D3456; color: #fff; padding: 10px 14px; text-align: left; }}
  td    {{ padding: 9px 14px; border-bottom: 1px solid #dee2e6; }}
  tr:hover td {{ background: #f8f9fa; }}
  .box  {{ display: inline-block; padding: 16px 24px; border-radius: 6px; background: #f8f9fa; margin: 6px; text-align: center; }}
  .num  {{ font-size: 2rem; font-weight: bold; color: #0D3456; }}
  .lbl  {{ color: #6c757d; font-size: .85rem; }}
  .meta {{ color: #6c757d; font-size: .9rem; margin: 3px 0; }}
</style>
</head>
<body>
<h1>Boundaryless Release Report</h1>
<p class="meta">Run: <code>{run.run_id}</code> &nbsp;|&nbsp; Commit: <code>{run.git_commit}</code> &nbsp;|&nbsp; Mode: <code>{run.mode}</code></p>
<p class="meta">Started: {run.started_at} &nbsp;|&nbsp; Finished: {run.finished_at}</p>

<h2>Decision: <span class="badge" style="background:{d_color}">{decision}</span></h2>

<div>
  <div class="box"><div class="num">{run.total}</div><div class="lbl">Total</div></div>
  <div class="box"><div class="num" style="color:#198754">{run.passed}</div><div class="lbl">Passed</div></div>
  <div class="box"><div class="num" style="color:#dc3545">{run.failed}</div><div class="lbl">Failed</div></div>
  <div class="box"><div class="num">{pct}%</div><div class="lbl">Pass Rate</div></div>
</div>

<h2>Module Status</h2>
<table>
  <thead><tr><th>Module</th><th>Status</th><th>Passed / Total</th></tr></thead>
  <tbody>{module_rows}</tbody>
</table>

{failures_section}

<hr>
<p class="meta">Generated by testctl &mdash; {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</p>
</body>
</html>"""

        output_path.write_text(html)
